### ISSUE TITLE
Maintain uniques when ID is set retroactively

### ISSUE THREAD

**Issue by paulfalgout** [disqus/backbone.uniquemodel#13]
This would be super useful in cases where multiple views have a new model that gets saved.  It is difficult to update those models to the uniquemodel version without this functionality.  @jfschwarz 's commit here seems like it would do the trick.

https://github.com/jfschwarz/backbone.uniquemodel/commit/e922f72b2fc534c4eff96236427a6cde5b8f5db1

**Comment by benvinegar** [comment]
See #15
