### ISSUE TITLE
Can't access Underscore

### ISSUE THREAD

**Issue by trezy** [disqus/backbone.uniquemodel#19]
Most Backbone plugins have hard dependencies on both Backbone _and_ Underscore. This one doesn't and, as a result, fails to work properly in my Node application: http://github.com/trezy/Turk

**Comment by BYK** [comment]
I don't think this is the library's fault.

**Comment by BYK** [comment]
Can you point me to the relevant part in your repo so I can have a look.

**Comment by trezy** [comment]
I ended up working around my issues since `backbone.uniquemodel` didn't quite do what I needed it to do. However, you're right, it's not actually the library's fault. It's related to the way that scoping works in the Node runtime inside of Electron (atom-shell).

The PR I submitted definitely isn't necessary to use this library in the browser and it may not even have any issues in a standard Node environment. However, it is necessary for compatibility with Electron.

**Comment by BYK** [comment]
I think this is something `Electron` should fix then right?
